//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cricketer_Details
    {
        public int Details_ID { get; set; }
        public Nullable<int> Cricketer_ID { get; set; }
        public string Team { get; set; }
        public Nullable<int> ODI_Runs { get; set; }
        public Nullable<int> Test_Runs { get; set; }
        public Nullable<int> Wickets { get; set; }
    
        public virtual Cricketer Cricketer { get; set; }
    }
}
